insert into ComodidadesCondominio (id, Condominio_id, nome) values (1, 22, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (2, 21, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (3, 27, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (4, 10, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (5, 21, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (6, 26, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (7, 3, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (8, 23, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (9, 8, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (10, 21, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (11, 8, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (12, 6, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (13, 3, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (14, 1, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (15, 23, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (16, 1, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (17, 8, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (18, 3, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (19, 29, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (20, 4, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (21, 18, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (22, 9, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (23, 21, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (24, 10, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (25, 19, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (26, 7, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (27, 18, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (28, 16, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (29, 28, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (30, 3, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (31, 30, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (32, 10, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (33, 19, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (34, 29, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (35, 6, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (36, 28, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (37, 26, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (38, 29, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (39, 29, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (40, 19, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (41, 6, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (42, 11, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (43, 12, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (44, 11, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (45, 17, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (46, 29, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (47, 13, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (48, 2, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (49, 25, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (50, 9, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (51, 12, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (52, 3, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (53, 4, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (54, 30, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (55, 3, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (56, 3, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (57, 24, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (58, 26, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (59, 5, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (60, 27, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (61, 8, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (62, 7, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (63, 14, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (64, 5, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (65, 24, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (66, 18, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (67, 3, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (68, 15, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (69, 26, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (70, 7, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (71, 17, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (72, 2, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (73, 16, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (74, 4, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (75, 30, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (76, 10, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (77, 20, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (78, 8, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (79, 25, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (80, 28, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (81, 10, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (82, 21, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (83, 21, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (84, 8, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (85, 15, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (86, 26, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (87, 23, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (88, 11, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (89, 29, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (90, 25, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (91, 26, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (92, 3, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (93, 30, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (94, 8, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (95, 28, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (96, 5, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (97, 12, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (98, 25, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (99, 5, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (100, 29, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (101, 7, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (102, 13, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (103, 9, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (104, 23, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (105, 1, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (106, 9, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (107, 20, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (108, 4, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (109, 10, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (110, 5, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (111, 28, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (112, 28, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (113, 26, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (114, 24, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (115, 1, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (116, 21, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (117, 15, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (118, 23, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (119, 25, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (120, 17, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (121, 30, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (122, 16, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (123, 27, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (124, 12, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (125, 1, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (126, 10, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (127, 4, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (128, 16, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (129, 21, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (130, 20, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (131, 24, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (132, 29, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (133, 5, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (134, 19, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (135, 30, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (136, 22, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (137, 1, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (138, 18, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (139, 4, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (140, 27, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (141, 5, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (142, 23, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (143, 23, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (144, 2, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (145, 4, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (146, 4, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (147, 12, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (148, 2, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (149, 6, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (150, 10, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (151, 10, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (152, 16, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (153, 25, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (154, 30, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (155, 5, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (156, 24, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (157, 4, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (158, 26, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (159, 28, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (160, 5, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (161, 26, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (162, 14, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (163, 23, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (164, 11, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (165, 17, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (166, 9, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (167, 5, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (168, 12, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (169, 28, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (170, 9, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (171, 3, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (172, 21, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (173, 9, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (174, 6, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (175, 5, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (176, 17, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (177, 13, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (178, 22, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (179, 1, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (180, 12, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (181, 20, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (182, 28, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (183, 24, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (184, 12, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (185, 16, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (186, 10, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (187, 15, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (188, 17, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (189, 24, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (190, 6, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (191, 4, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (192, 8, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (193, 25, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (194, 29, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (195, 20, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (196, 29, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (197, 27, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (198, 24, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (199, 28, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (200, 9, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (201, 26, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (202, 19, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (203, 3, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (204, 6, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (205, 26, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (206, 26, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (207, 13, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (208, 17, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (209, 7, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (210, 28, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (211, 10, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (212, 1, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (213, 4, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (214, 12, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (215, 1, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (216, 12, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (217, 2, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (218, 2, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (219, 28, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (220, 7, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (221, 1, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (222, 29, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (223, 21, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (224, 29, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (225, 5, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (226, 9, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (227, 12, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (228, 28, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (229, 11, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (230, 20, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (231, 24, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (232, 9, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (233, 6, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (234, 23, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (235, 27, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (236, 19, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (237, 30, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (238, 18, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (239, 17, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (240, 17, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (241, 12, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (242, 16, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (243, 13, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (244, 12, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (245, 1, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (246, 13, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (247, 12, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (248, 29, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (249, 25, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (250, 4, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (251, 11, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (252, 17, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (253, 8, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (254, 28, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (255, 22, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (256, 1, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (257, 15, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (258, 4, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (259, 20, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (260, 18, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (261, 27, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (262, 29, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (263, 24, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (264, 15, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (265, 21, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (266, 9, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (267, 5, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (268, 13, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (269, 16, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (270, 3, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (271, 13, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (272, 23, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (273, 20, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (274, 22, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (275, 28, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (276, 16, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (277, 12, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (278, 3, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (279, 22, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (280, 14, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (281, 11, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (282, 23, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (283, 17, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (284, 29, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (285, 17, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (286, 25, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (287, 12, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (288, 6, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (289, 29, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (290, 18, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (291, 29, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (292, 19, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (293, 8, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (294, 13, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (295, 30, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (296, 28, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (297, 1, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (298, 30, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (299, 2, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (300, 28, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (301, 22, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (302, 11, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (303, 18, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (304, 3, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (305, 25, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (306, 1, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (307, 9, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (308, 10, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (309, 8, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (310, 24, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (311, 11, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (312, 29, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (313, 27, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (314, 18, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (315, 22, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (316, 9, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (317, 15, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (318, 16, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (319, 8, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (320, 15, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (321, 26, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (322, 7, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (323, 2, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (324, 6, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (325, 20, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (326, 18, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (327, 18, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (328, 12, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (329, 15, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (330, 6, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (331, 25, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (332, 12, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (333, 1, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (334, 16, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (335, 25, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (336, 20, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (337, 13, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (338, 13, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (339, 2, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (340, 18, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (341, 25, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (342, 8, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (343, 10, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (344, 23, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (345, 25, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (346, 14, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (347, 29, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (348, 9, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (349, 13, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (350, 21, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (351, 28, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (352, 13, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (353, 7, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (354, 9, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (355, 14, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (356, 20, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (357, 1, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (358, 25, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (359, 7, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (360, 9, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (361, 12, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (362, 12, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (363, 13, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (364, 2, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (365, 24, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (366, 4, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (367, 27, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (368, 1, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (369, 17, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (370, 26, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (371, 6, 'Piscina');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (372, 3, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (373, 28, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (374, 14, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (375, 6, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (376, 15, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (377, 18, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (378, 1, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (379, 4, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (380, 30, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (381, 9, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (382, 5, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (383, 28, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (384, 9, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (385, 24, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (386, 11, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (387, 18, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (388, 23, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (389, 1, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (390, 19, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (391, 30, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (392, 24, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (393, 5, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (394, 3, 'Acesso a Comércio Próximo');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (395, 24, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (396, 22, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (397, 14, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (398, 20, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (399, 15, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (400, 28, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (401, 6, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (402, 22, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (403, 29, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (404, 21, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (405, 13, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (406, 5, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (407, 26, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (408, 11, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (409, 12, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (410, 30, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (411, 19, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (412, 6, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (413, 4, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (414, 12, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (415, 6, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (416, 8, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (417, 27, 'Quadra Esportiva');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (418, 10, 'Área de Leitura');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (419, 7, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (420, 27, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (421, 18, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (422, 7, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (423, 16, 'Espaço Pet');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (424, 29, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (425, 22, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (426, 14, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (427, 14, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (428, 5, 'Jardim');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (429, 13, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (430, 2, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (431, 29, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (432, 29, 'Elevador');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (433, 18, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (434, 7, 'Segurança 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (435, 14, 'Estacionamento Coberto');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (436, 29, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (437, 13, 'Salão de Festas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (438, 23, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (439, 1, 'Playground');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (440, 29, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (441, 2, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (442, 16, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (443, 2, 'Biblioteca');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (444, 3, 'Área de Churrasco');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (445, 9, 'Academia');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (446, 30, 'Wi-Fi nas áreas comuns');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (447, 7, 'Lavanderia Compartilhada');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (448, 26, 'Salão de Jogos');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (449, 24, 'Área de Descanso');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (450, 16, 'Portaria 24 horas');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (451, 17, 'Sauna');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (452, 26, 'Sala de Cinema');
insert into ComodidadesCondominio (id, Condominio_id, nome) values (453, 5, 'Salão de Festas');
