insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (1, 'Demizz', 1272.65, 'Apartamento', 'xrymh', '66 Rockefeller Trail');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (2, 'Skyble', 536.33, 'Casa', 'dzmhh', '2 Fair Oaks Street');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (3, 'Bluezoom', 866.08, 'Apartamento', 'zwksr', '7435 Anniversary Avenue');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (4, 'Dabtype', 862.82, 'Apartamento', 'ubfnz', '0384 Carioca Junction');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (5, 'Kamba', 1154.38, 'Casa', 'ngfes', '7 6th Alley');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (6, 'Realpoint', 919.98, 'Apartamento', 'ycjix', '395 Hovde Junction');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (7, 'Mudo', 1558.5, 'Apartamento', 'xgwca', '66 Rusk Road');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (8, 'Avaveo', 1977.53, 'Apartamento', 'sudxb', '7557 Rowland Circle');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (9, 'Feedfire', 1667.01, 'Casa', 'znoee', '73 Shelley Avenue');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (10, 'Demizz', 485.89, 'Apartamento', 'ysueq', '37 5th Parkway');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (11, 'Skaboo', 893.27, 'Casa', 'ppndx', '18 Browning Road');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (12, 'Fivespan', 578.43, 'Casa', 'idprb', '20 7th Pass');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (13, 'Quinu', 604.73, 'Casa', 'oehls', '10 Spaight Street');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (14, 'Fliptune', 741.45, 'Apartamento', 'nuniu', '6786 Carberry Road');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (15, 'Meejo', 1380.84, 'Apartamento', 'swipw', '91 Alpine Point');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (16, 'Twinte', 638.79, 'Apartamento', 'fwmth', '9724 Clyde Gallagher Park');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (17, 'Photojam', 1465.02, 'Casa', 'cudfd', '8158 Gulseth Point');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (18, 'Blogtags', 850.46, 'Casa', 'krrzq', '1 Di Loreto Street');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (19, 'Wikizz', 1180.85, 'Casa', 'sxjie', '454 Dixon Drive');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (20, 'Edgewire', 993.64, 'Casa', 'lfhji', '2 Crescent Oaks Hill');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (21, 'Mymm', 1094.15, 'Casa', 'epchj', '7 Bartillon Street');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (22, 'Yodo', 907.38, 'Apartamento', 'gsqis', '42406 Nelson Alley');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (23, 'Janyx', 1806.2, 'Apartamento', 'wlhjw', '1595 Brickson Park Crossing');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (24, 'Vidoo', 1402.84, 'Apartamento', 'nxkvt', '8395 Heffernan Avenue');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (25, 'Zoonder', 1507.48, 'Casa', 'svfxh', '6246 Blaine Plaza');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (26, 'Oyondu', 802.29, 'Apartamento', 'ojdjp', '88 Talmadge Point');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (27, 'Meemm', 1788.53, 'Apartamento', 'rpwlx', '2 Northview Circle');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (28, 'Trilith', 1798.42, 'Apartamento', 'kqnqo', '758 High Crossing Drive');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (29, 'Demivee', 1747.2, 'Casa', 'xgfby', '27 Atwood Place');
insert into condominio (id, nome, valorMensal, tipo, restricoes, endereco) values (30, 'Skyvu', 475.84, 'Apartamento', 'pzuyq', '05 Oneill Park');
