insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (1, 351, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Comerciais', 'Zona Oeste', 9.24);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (2, 352, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Sul', 8.68);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (3, 353, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Oeste', 9.36);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (4, 354, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Comerciais', 'Zona Norte', 7.43);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (5, 355, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Comerciais', 'Zona Leste', 9.85);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (6, 356, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Norte', 9.16);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (7, 357, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Norte', 9.56);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (8, 358, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Oeste', 6.32);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (9, 359, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 7.82);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (10, 360, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Comerciais', 'Zona Norte', 6.2);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (11, 361, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Comerciais', 'Zona Oeste', 9.08);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (12, 362, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Norte', 6.89);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (13, 363, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis de Luxo', 'Zona Sul', 6.12);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (14, 364, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Leste', 6.23);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (15, 365, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis de Luxo', 'Zona Leste', 6.69);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (16, 366, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 8.63);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (17, 367, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Sul', 6.02);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (18, 368, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Sul', 9.07);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (19, 369, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Norte', 6.2);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (20, 370, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Sul', 7.1);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (21, 371, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Leste', 9.08);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (22, 372, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis de Luxo', 'Zona Leste', 6.45);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (23, 373, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Norte', 8.27);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (24, 374, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 6.59);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (25, 375, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Leste', 7.23);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (26, 376, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Sul', 8.57);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (27, 377, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Comerciais', 'Zona Leste', 7.65);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (28, 378, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis de Luxo', 'Zona Leste', 7.43);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (29, 379, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Leste', 9.54);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (30, 380, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Sul', 7.55);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (31, 381, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis de Luxo', 'Zona Oeste', 6.55);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (32, 382, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 8.07);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (33, 383, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Leste', 6.21);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (34, 384, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Norte', 6.45);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (35, 385, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Norte', 9.24);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (36, 386, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Norte', 9.82);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (37, 387, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Norte', 8.01);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (38, 388, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Norte', 7.27);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (39, 389, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Leste', 6.89);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (40, 390, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis de Luxo', 'Zona Leste', 9.16);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (41, 391, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Comerciais', 'Zona Oeste', 9.12);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (42, 392, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Comerciais', 'Zona Sul', 9.82);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (43, 393, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 8.9);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (44, 394, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Sul', 7.9);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (45, 395, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Comerciais', 'Zona Oeste', 6.96);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (46, 396, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 6.82);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (47, 397, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis de Luxo', 'Zona Norte', 8.91);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (48, 398, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Comerciais', 'Zona Leste', 9.13);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (49, 399, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Leste', 9.22);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (50, 400, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Sul', 7.1);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (51, 401, 'Corretor de Imoveis de Luxo', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 7.3);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (52, 402, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis Residenciais', 'Zona Oeste', 8.67);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (53, 403, 'Corretor de Imoveis Residenciais', 'Corretor de Imoveis de Luxo', 'Zona Norte', 6.56);
insert into Corretor (id, Usuario_id, experiencia, especializacao, areaDeAtuacao, comissao) values (54, 404, 'Corretor de Imoveis Comerciais', 'Corretor de Imoveis de Luxo', 'Zona Leste', 8.99);
